Pull before bush in the second job
Previous error log:
```
Run git config user.name "github-actions[bot]"
  git config user.name "github-actions[bot]"
  git config user.email "github-actions[bot]@users.noreply.github.com"
  git add data/*.csv
  timestamp=$(TZ='Asia/Jakarta' date +'%a, %F at %H:%M %Z')
  git commit -m "Updated: ${timestamp}" || exit 0
  git push
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.13/x64/lib
[main aeed674] Updated: Tue, 2022-08-16 at 21:21 WIB
 1 file changed, 241 insertions(+)
 create mode 100644 data/unit_konstruksi.csv
To https://github.com/civilacademy/daftar-skk-bnsp
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/civilacademy/daftar-skk-bnsp'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.
```